//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.01.23 at 01:08:36 PM IST 
//


package netimex.util;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the netimex.util package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: netimex.util
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link SetCustomerData }
     * 
     */
    public SetCustomerData createSetCustomerData() {
        return new SetCustomerData();
    }

    /**
     * Create an instance of {@link CustomerDataTest }
     * 
     */
    public CustomerDataTest createCustomerDataTest() {
        return new CustomerDataTest();
    }

    /**
     * Create an instance of {@link SetCustomerDataResponse }
     * 
     */
    public SetCustomerDataResponse createSetCustomerDataResponse() {
        return new SetCustomerDataResponse();
    }

    /**
     * Create an instance of {@link SetCustomerDataResponse2 }
     * 
     */
    public SetCustomerDataResponse2 createSetCustomerDataResponse2() {
        return new SetCustomerDataResponse2();
    }

    /**
     * Create an instance of {@link GetCustomerData }
     * 
     */
    public GetCustomerData createGetCustomerData() {
        return new GetCustomerData();
    }

    /**
     * Create an instance of {@link GetCustomerDataRequest }
     * 
     */
    public GetCustomerDataRequest createGetCustomerDataRequest() {
        return new GetCustomerDataRequest();
    }

    /**
     * Create an instance of {@link GetCustomerDataResponse }
     * 
     */
    public GetCustomerDataResponse createGetCustomerDataResponse() {
        return new GetCustomerDataResponse();
    }

}
